.TH "ifuse" 1
.SH NAME
ifuse \- Mount directories of an iOS device locally using fuse.
.SH SYNOPSIS
.B ifuse MOUNTPOINT [OPTIONS]

.SH DESCRIPTION

Mount directories of an iOS device locally using fuse. By default the media
directory is mounted, options allow to also mount the sandbox container of an
app, an app's documents folder or even the root filesystem on jailbroken
devices.

Example:

$ ifuse /media/iPhone \-\-root

This mounts the root filesystem of the first attached device on
this computer in the directory /media/iPhone.

Regular users are able to unmount fuse mounts using "fusermount -u MOUNTPOINT".

.SH OPTIONS
.TP
.B \-o opt,[opt...] 
mount options.
.TP
.B \-u, \-\-udid UDID
mount specific device by UDID.
.TP
.B \-n, \-\-network
connect to network device even if available via USB.
.TP
.B \-h, \-\-help
print usage information.
.TP
.B \-V, \-\-version
print version.
.TP
.B \-d, \-\-debug
enable libimobiledevice communication debugging.
.TP
.B \-\-documents APPID
mount 'Documents' folder of app identified by APPID.
.TP
.B \-\-container APPID
mount sandbox root of an app identified by APPID.
.TP
.B \-\-list-apps
list installed apps that have file sharing enabled.
.TP
.B \-\-root
mount root file system (jailbroken device required).

.SH AUTHOR
Julien Lavergne (man page)

Martin Szulecki

Matt Colyer

Nikias Bassen

.SH SEE ALSO
fusermount(1)

.SH ON THE WEB
https://libimobiledevice.org

https://github.com/libimobiledevice/ifuse
